export const articles = [{
  content: 'Das hat vor allem etwas mit der Übersichtlichkeit der Seite zu tun. Wenn du dein Profil einrichtest, kannst du deinem Podcast verschiedenen Kategorien zuordnen. So wissen Besucher:innen deines Profils gleich, um welche Themen sich dein Format inhaltlich dreht und zu welchen Themen du gerne sprechen möchtest. Besucher:innen können nach Schlagworten suchen und finden sofort die passenden Profile zu ihrem Thema.</p><p>Damit es schön praktisch und übersichtlich bleibt, haben wir uns für so genannte „hard coded tags” entschieden. Das heißt, die vorgegebenen Kategorien sind fix und können von dir nicht verändert oder um neue Schlagworte erweitert werden. Dadurch findest du vielleicht nicht die eine Kategorie bzw. „tags“, die dein Format perfekt beschreiben. Aber es erleichtert die Bedienung der Seite immens und stellt ohnehin nur eine erste grobe Einordnung deines Formats dar. In der Beschreibung auf deinem Profil kannst du nämlich noch viel spezieller und genauer auf dich und die Inhalte deines Podcasts eingehen. Wenn du findest, dass wir (trotz intensiver Recherche) eine ganz wichtige Themen-Kategorie vergessen haben und unbedingt ergänzen sollten, dann schreibe uns doch einfach <a href="https://github.com/podcasterinnen/chosen-client/issues/161" target="_blank">hier auf Github einen Kommentar</a>.',
  date: '2018-12-27',
  id: 1,
  title: 'Wir sagen Danke',
}, {
  content: 'Das hat vor allem etwas mit der Übersichtlichkeit der Seite zu tun. Wenn du dein Profil einrichtest, kannst du deinem Podcast verschiedenen Kategorien zuordnen. So wissen Besucher:innen deines Profils gleich, um welche Themen sich dein Format inhaltlich dreht und zu welchen Themen du gerne sprechen möchtest. Besucher:innen können nach Schlagworten suchen und finden sofort die passenden Profile zu ihrem Thema.</p><p>Damit es schön praktisch und übersichtlich bleibt, haben wir uns für so genannte „hard coded tags” entschieden. Das heißt, die vorgegebenen Kategorien sind fix und können von dir nicht verändert oder um neue Schlagworte erweitert werden. Dadurch findest du vielleicht nicht die eine Kategorie bzw. „tags“, die dein Format perfekt beschreiben. Aber es erleichtert die Bedienung der Seite immens und stellt ohnehin nur eine erste grobe Einordnung deines Formats dar. In der Beschreibung auf deinem Profil kannst du nämlich noch viel spezieller und genauer auf dich und die Inhalte deines Podcasts eingehen. Wenn du findest, dass wir (trotz intensiver Recherche) eine ganz wichtige Themen-Kategorie vergessen haben und unbedingt ergänzen sollten, dann schreibe uns doch einfach <a href="https://github.com/podcasterinnen/chosen-client/issues/161" target="_blank">hier auf Github einen Kommentar</a>.',
  date: '2018-12-26',
  id: 0,
  title: 'Juhu wir sind online',
}]