export const articles = [{
  content: 'Liebe Podcaster*innen,</p><p>still ist es um uns geworden. Dafür wird es in der Welt um uns herum immer lauter.</p><p>Hier ein Update, ein Lebenszeichen und ein Aufruf von Michaela und Daniela.</p><p>Vor knapp fünf Jahren ging unsere Plattform Podcasterinnen.org online. Das war 2018. Seitdem hat sich privat und beruflich vieles bei uns getan. Dazwischen passiert(e) noch eine Pandemie. Viel los also, vieles was uns daran hinderte konsequent genug die Arbeit an der Plattform wieder aufzunehmen.</p><p>Wir haben in den letzten 2 Jahren mehrfach Anlauf genommen um euch mit neuen Funktionen und einem eigenen Podcast zu versorgen. Umsetzen konnten wir davon am Ende aus zeitlichen Gründen nichts.</p><p>Deshalb kommt hier unser Aufruf:</p><p>Wir suchen Nachfolger*innen. Es sollten sich mindestens 2 Personen finden, von der eine programmieren kann.</p><p>Je mehr Leute ihr seid, umso besser. Es gibt noch viele offene Ideen an Funktionen, die sich über eine Umsetzung sehr freuen.</p><p>Wir hoffen, dass sich bis Ende des Jahres Menschen finden, die Zeit und Lust haben, Podcasterinnen.org auf ein neues Level zu heben. Potenzial ist da.</p><p>Wenn sich bis Ende 2023 keine Nachfolge finden lässt, werden wir den Dienst einstellen.</p><p>Bitte meldet euch via Mail, auch gerne mit euren Fragen, an contact@podcasterinnen.org</p><p></p><p>Danke und liebe Grüße</p><p>Michaela & Daniela',
  date: '2023-11-29',
  id: 1,
  title: 'Wir suchen Nachfolger:innen',
  url: '2023-11-29-wir-suchen-nachfolgerinnen'
}, {
  content: 'Liebe Podcastpersonen, liebe Podcasterinnen, liebe Community,</p><p>vielleicht hat es di*er ein oder andere schon mitbekommen: Wir, das Team hinter podcasterinnen.org, arbeiten seit April an der Website, auf der ihr hier gerade gelandet seid: podcasterinnen.org. Und nun im Dezember können wir es voller Freude sagen: Wir sind online.</p><p>Wir haben es uns mit dieser Website zur Aufgabe gemacht, Podcasterinnen sowie nicht-binäre Podcastende und ihre Formate sichtbarer zu machen. Nach dem Vorbild von <a href="https://speakerinnen.org/" target="_blank">speakerinnen.org</a> möchten wir die Auffindbarkeit von Podcastpersonen und Podcasterinnen über Themen und Inhalte vereinfachen. Mehr zu unserem Anliegen könnt ihr <a href="/about">hier nachlesen</a>.</p><p>Und dann seid ihr gefragt:</p><ul><li>Ihr als nicht-binäre Podcastpersonen und als Podcasterinnen – denn ihr könnt euch ab sofort <a href="/session">hier ein aussagekräftiges Profil anlegen</a>;</li><li>und alle anderen auch – denn ihr könnt euch ab sofort <a href="/podcasterinnen">hier nach Personen umsehen</a>, die zu eurem Thema, eurem Workshop oder eurem Vortrag passen.</li></ul><p>Unser Ziel: Wir wollen diverse Teams, unterschiedliche Perspektiven und keine Ausreden mehr, warum genau zu diesem Vortrag mal wieder keine nicht-binäre Podcastperson oder Podcasterin zu finden war.</p><p>Wir freuen uns, wenn ihr die Idee von podcasterinnen.org weiter tragt und in euren Podcasts und/oder auf euren Blogs auf unsere Website und das Anliegen dahinter hinweist.</p><p>Am Schluss gilt es, Menschen Danke zu sagen:</p><ul><li>Lara, Letty, Lilli und Ulrike für die erste Testrunde, euer Feedback war Gold wert;</li><li>Becci für das unermüdliche Korrigieren unserer Texte und für die Hilfe, geschlechter- und diskriminierungssensible Sprache möglichst gut umzusetzen;</li><li>Jamie für das Beantworten unserer Fragen, nicht-binäre Podcastpersonen anzusprechen und das Feedback, dass wir vielleicht schon mit unserer URL an Grenzen stoßen;</li><li>Hukl für all die „Also wenn ich ihr wärt, würde ich selbst hosten“-Sätze und die Hilfe, podcasterinnen.org dann auch wirklich selbst zu hosten;</li><li>Nitram und Richi für das Aufdecken und Dokumentieren einiger Sicherheitslücken und Bugs;</li><li>Bianca, Florian, Stefan und Eric für ihre Hilfe im Umgang mit Elixir, Phoenix, A11y und dem deutschen Datenschutz.</li></ul><p>Es war wunderbar, mit euch zusammenzuarbeiten, Neues zu lernen, sich auszutauschen, Dinge zu verwerfen und Verworfenes wieder aufzugreifen. Danke!</p><p>Und nun heißt es endgültig: podcasterinnen.org ist eröffnet!',
  date: '2018-12-22',
  id: 0,
  title: 'Juhu wir sind online',
  url: '2018-12-22-juhu-wir-sind-online'
}]