// Session Types
export const LOCAL_STORAGE_USER_ID = 'CHOSEN_USER_ID'

// Session States
export const INVALID = 'INVALID'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_IN_PROGRESS = 'FORGOT_PASSWORD_IN_PROGRESS'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const LOGGED_IN = 'LOGGED_IN'
export const REGISTRATION_IN_PROGRESS = 'REGISTRATION_IN_PROGRESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTERED = 'REGISTERED'
export const UNKNOWN = 'UNKNOWN'
